FROM python:3.8-slim

COPY src/main/python/requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt

COPY src/main/python /app

COPY project.properties /app

ENTRYPOINT ["python3", "-u", "kafka-producer.py"]
